DROP TABLE IF EXISTS [WishGiftTag];
CREATE TABLE [WishGiftTag] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[WishPurchaseId] UNIQUEIDENTIFIER NOT NULL,
	[FromText] NVARCHAR(500) NULL,
	[ToText] NVARCHAR(500) NULL
);
