CREATE TABLE [WishGroupCollaborationMember] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    [WishUserGroupId] UNIQUEIDENTIFIER NOT NULL,
    [WishGroupCollaborationId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [IsAdmin] BIT NOT NULL,
    [CreatedDate] DATETIMEOFFSET(5) DEFAULT GETUTCDATE() NOT NULL,
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
    [DeletedDate] DATETIMEOFFSET(5) NULL,
    [DeletedByUserId] UNIQUEIDENTIFIER NULL
);

DROP TABLE [WishGroupCollaborationUser];
