CREATE TABLE [WishGroupCollaboration] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    [WishUserGroupId] UNIQUEIDENTIFIER NOT NULL,
    [Title] NVARCHAR(MAX) NULL,
    [AvatarColour] NVARCHAR(24) NULL,
    [AvatarEmoji] NVARCHAR(24) NULL,
    [CreatedByUserId] UNIQUEIDENTIFIER NULL,
    [CreatedDate] DATETIMEOFFSET(5) DEFAULT GETUTCDATE() NOT NULL,
    [DeletedByUserId] UNIQUEIDENTIFIER NULL,
    [DeletedDate] DATETIMEOFFSET(5) NULL
);

CREATE TABLE [WishGroupCollaborationUser] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    [WishGroupCollaborationId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL
);

ALTER TABLE [WishGroupWish]
ADD [WishGroupCollaborationId] UNIQUEIDENTIFIER NULL;
