ALTER TABLE [WishUserGroupUser] ADD [DeletedDate] DATETIMEOFFSET(5) NULL;
ALTER TABLE [WishUserGroupUser] ADD [DeletedByUserId] UNIQUEIDENTIFIER NULL;

ALTER TABLE [WishGroupWish] ADD [DeletedDate] DATETIMEOFFSET(5) NULL;
ALTER TABLE [WishGroupWish] ADD [DeletedByUserId] UNIQUEIDENTIFIER NULL;
