CREATE TABLE [WishPurchaseNote]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[WishPurchaseId] UNIQUEIDENTIFIER NOT NULL,
	[Note] NVARCHAR(150) NOT NULL,
	[CreatedDate] DATETIMEOFFSET(5) DEFAULT GETUTCDATE() NOT NULL,
	[CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
	[DeletedDate] DATETIMEOFFSET(5) NULL,
	[DeletedByUserId] UNIQUEIDENTIFIER NULL
);
